// Code generated by gtrace. DO NOT EDIT.

package spooler

import (
	"context"
)

// Compose returns a new ClientTrace which has functional fields composed
// both from t and x.
func (t ClientTrace) Compose(x ClientTrace) (ret ClientTrace) {
	switch {
	case t.OnConnect == nil:
		ret.OnConnect = x.OnConnect
	case x.OnConnect == nil:
		ret.OnConnect = t.OnConnect
	default:
		h1 := t.OnConnect
		h2 := x.OnConnect
		ret.OnConnect = func(network string, addr string) func(error) {
			r1 := h1(network, addr)
			r2 := h2(network, addr)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(e error) {
					r1(e)
					r2(e)
				}
			}
		}
	}
	switch {
	case t.OnRequest == nil:
		ret.OnRequest = x.OnRequest
	case x.OnRequest == nil:
		ret.OnRequest = t.OnRequest
	default:
		h1 := t.OnRequest
		h2 := x.OnRequest
		ret.OnRequest = func(c context.Context, r RequestTrace) func(error) {
			r1 := h1(c, r)
			r2 := h2(c, r)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(e error) {
					r1(e)
					r2(e)
				}
			}
		}
	}
	switch {
	case t.OnMalformedResponse == nil:
		ret.OnMalformedResponse = x.OnMalformedResponse
	case x.OnMalformedResponse == nil:
		ret.OnMalformedResponse = t.OnMalformedResponse
	default:
		h1 := t.OnMalformedResponse
		h2 := x.OnMalformedResponse
		ret.OnMalformedResponse = func(c context.Context, r RequestTrace, e error) {
			h1(c, r, e)
			h2(c, r, e)
		}
	}
	return ret
}
func (t ClientTrace) onConnect(network string, addr string) func(error) {
	fn := t.OnConnect
	if fn == nil {
		return func(error) {
			return
		}
	}
	res := fn(network, addr)
	if res == nil {
		return func(error) {
			return
		}
	}
	return res
}
func (t ClientTrace) onRequest(c1 context.Context, r RequestTrace) func(error) {
	fn := t.OnRequest
	if fn == nil {
		return func(error) {
			return
		}
	}
	res := fn(c1, r)
	if res == nil {
		return func(error) {
			return
		}
	}
	return res
}
func (t ClientTrace) onMalformedResponse(c1 context.Context, r RequestTrace, e error) {
	fn := t.OnMalformedResponse
	if fn == nil {
		return
	}
	fn(c1, r, e)
}
