// Code generated by gtrace. DO NOT EDIT.

package spooler

// Compose returns a new ClientTrace which has functional fields composed
// both from t and x.
func (t ClientTrace) Compose(x ClientTrace) (ret ClientTrace) {
	return ret
}
