// Code generated by gtrace. DO NOT EDIT.

package httputil

import (
	"net/http"
)

// Compose returns a new ClientTrace which has functional fields composed
// both from t and x.
func (t ClientTrace) Compose(x ClientTrace) (ret ClientTrace) {
	ret.RoundTripper = t.RoundTripper.Compose(x.RoundTripper)
	return ret
}

// Compose returns a new RoundTripperTrace which has functional fields composed
// both from t and x.
func (t RoundTripperTrace) Compose(x RoundTripperTrace) (ret RoundTripperTrace) {
	switch {
	case t.OnRoundTrip == nil:
		ret.OnRoundTrip = x.OnRoundTrip
	case x.OnRoundTrip == nil:
		ret.OnRoundTrip = t.OnRoundTrip
	default:
		h1 := t.OnRoundTrip
		h2 := x.OnRoundTrip
		ret.OnRoundTrip = func(r *http.Request) func(*http.Response, error) {
			r1 := h1(r)
			r2 := h2(r)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(r *http.Response, e error) {
					r1(r, e)
					r2(r, e)
				}
			}
		}
	}
	switch {
	case t.OnConnect == nil:
		ret.OnConnect = x.OnConnect
	case x.OnConnect == nil:
		ret.OnConnect = t.OnConnect
	default:
		h1 := t.OnConnect
		h2 := x.OnConnect
		ret.OnConnect = func(network string, addr string) func(error) {
			r1 := h1(network, addr)
			r2 := h2(network, addr)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(e error) {
					r1(e)
					r2(e)
				}
			}
		}
	}
	return ret
}
func (t RoundTripperTrace) onRoundTrip(r *http.Request) func(*http.Response, error) {
	fn := t.OnRoundTrip
	if fn == nil {
		return func(*http.Response, error) {
			return
		}
	}
	res := fn(r)
	if res == nil {
		return func(*http.Response, error) {
			return
		}
	}
	return res
}
func (t RoundTripperTrace) onConnect(network string, addr string) func(error) {
	fn := t.OnConnect
	if fn == nil {
		return func(error) {
			return
		}
	}
	res := fn(network, addr)
	if res == nil {
		return func(error) {
			return
		}
	}
	return res
}
